version: '3'

services:
  db:
    image: mongo
    container_name: matricula_download_db
    restart: unless-stopped
    volumes:
      - matricula_download_db_volume:/data/db
    ports:
      - 27017:27017

volumes:
  matricula_download_db_volume:
